import Link from "next/link";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { CheckCircle2, Code2, Cpu, Terminal } from "lucide-react";

const aiLogs = [
  {
    time: "2026-05-29 14:18 UTC",
    title: "Prescriptive Fivetran Payload Drafted",
    summary: "Gemini analyzed shortage velocity and generated the connector schema for emergency inventory reconciliation.",
    details: "Drafted a JSON payload for Fivetran with source mappings from vendor ERP, hospital inventory telemetry, and alert feeds. Marked connector as manual approval before execution.",
    tag: "Draft",
  },
  {
    time: "2026-05-28 09:42 UTC",
    title: "Supply Pivot Recommended",
    summary: "AI identified Lidocaine HCl risk at Southern Cross Clinic and recommended urgent supplier reallocation.",
    details: "Recommended moving stock from low-risk Westside sites to high-demand South regions using predicted burn models and shipment ETA windows.",
    tag: "Recommendation",
  },
  {
    time: "2026-05-27 21:07 UTC",
    title: "Anomaly Detected in Cold Chain Feed",
    summary: "Gemini flagged delayed audit syncs and elevated the event to the monitoring dashboard.",
    details: "Auto-generated an incident brief for the transfer pipeline team, with remediation steps for restoring hourly sensor ingestion.",
    tag: "Alert",
  },
];

const tagVariant = (tag: string) => {
  if (tag === "Alert") return "destructive";
  if (tag === "Recommendation") return "secondary";
  return "default";
};

export default function AiLogsPage() {
  return (
    <main className="min-h-screen bg-slate-950 text-slate-100">
      <div className="mx-auto max-w-6xl px-4 py-8 sm:px-6 lg:px-8">
        <div className="mb-6 flex flex-wrap items-center justify-between gap-3">
          <div>
            <p className="text-sm uppercase tracking-[0.3em] text-emerald-400/70">AI Decision History</p>
            <h1 className="mt-2 text-3xl font-semibold tracking-tight text-white">Gemini AI Logs</h1>
            <p className="mt-2 max-w-2xl text-sm text-slate-400">
              Inference history and infrastructure drafts from the enterprise prescriptive engine.
            </p>
          </div>
          <div className="flex flex-wrap gap-2">
            <Link
              href="/"
              className="rounded-full border border-emerald-700 bg-emerald-950/40 px-4 py-2 text-sm font-medium text-emerald-300 transition hover:bg-emerald-700/20"
            >
              Dashboard
            </Link>
            <Link
              href="/inventory-forecast"
              className="rounded-full border border-slate-700 bg-slate-900/80 px-4 py-2 text-sm font-medium text-slate-200 transition hover:bg-slate-800"
            >
              Inventory Forecast
            </Link>
            <Link
              href="/transfer-pipelines"
              className="rounded-full border border-slate-700 bg-slate-900/80 px-4 py-2 text-sm font-medium text-slate-200 transition hover:bg-slate-800"
            >
              Transfer Pipelines
            </Link>
          </div>
        </div>

        <div className="grid gap-4 lg:grid-cols-3">
          <Card className="border-emerald-700/40 bg-slate-900/80">
            <CardHeader>
              <div className="flex items-center gap-3">
                <Cpu className="h-5 w-5 text-emerald-300" />
                <CardTitle>Decision Throughput</CardTitle>
              </div>
              <CardDescription>Number of AI reasoning actions completed in the last 24 hours.</CardDescription>
            </CardHeader>
            <CardContent className="grid gap-3">
              <div className="text-3xl font-semibold text-white">12</div>
              <p className="text-sm text-slate-400">Enterprise-grade reasoning actions executed across supply chain domains.</p>
            </CardContent>
          </Card>
          <Card className="border-teal-700/40 bg-slate-900/80">
            <CardHeader>
              <div className="flex items-center gap-3">
                <Terminal className="h-5 w-5 text-teal-300" />
                <CardTitle>Drafted Assets</CardTitle>
              </div>
              <CardDescription>Infrastructure definitions and connector payloads generated by Gemini.</CardDescription>
            </CardHeader>
            <CardContent className="grid gap-3">
              <div className="text-3xl font-semibold text-white">7</div>
              <p className="text-sm text-slate-400">Mock drafts currently staged for human review and deployment.</p>
            </CardContent>
          </Card>
          <Card className="border-slate-700/50 bg-slate-900/80">
            <CardHeader>
              <div className="flex items-center gap-3">
                <CheckCircle2 className="h-5 w-5 text-slate-300" />
                <CardTitle>Approval Ready</CardTitle>
              </div>
              <CardDescription>AI reasoning artifacts waiting for executive sign-off.</CardDescription>
            </CardHeader>
            <CardContent className="grid gap-3">
              <div className="text-3xl font-semibold text-white">3</div>
              <p className="text-sm text-slate-400">High-confidence recommendations primed for operational handoff.</p>
            </CardContent>
          </Card>
        </div>

        <div className="mt-8 space-y-4">
          {aiLogs.map((log) => (
            <Card key={log.time} className="border-slate-700/60 bg-slate-900/85 shadow-xl shadow-slate-950/20">
              <CardHeader>
                <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
                  <div>
                    <div className="text-sm uppercase tracking-[0.18em] text-slate-500">{log.time}</div>
                    <CardTitle className="text-lg text-white">{log.title}</CardTitle>
                  </div>
                  <Badge variant={tagVariant(log.tag)}>{log.tag}</Badge>
                </div>
              </CardHeader>
              <CardContent className="space-y-4 border-t border-slate-800/80 pt-4">
                <p className="text-sm leading-7 text-slate-300">{log.summary}</p>
                <div className="rounded-2xl border border-slate-800 bg-slate-950/90 p-4 text-sm text-slate-200">
                  <pre className="whitespace-pre-wrap break-words font-mono text-slate-200">{log.details}</pre>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>
    </main>
  );
}
