import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

const aiLogEvents = [
  {
    time: "2026-05-29 14:18 UTC",
    title: "Prescriptive Fivetran Payload Drafted",
    alert: "Regional Albuterol shortage at Northeast General",
    reasoning: "Gemini correlated burn forecasts with supplier availability and generated a live connector schema for emergency replenishment.",
    payload: `{
  "service": "fivetran",
  "group_id": "duro-net-prod",
  "config": {
    "schema": "supply_chain",
    "table": "emergency_inventory",
    "source": "hospital_telemetry",
    "destination": "warehouse_reporting"
  }
}`,
    tag: "Draft",
  },
  {
    time: "2026-05-28 09:42 UTC",
    title: "Supply Pivot Recommended",
    alert: "Lidocaine HCl remaining below 5 days in South region",
    reasoning: "Shifted inventory from Westside and prioritized vendor allocations to meet high-risk facility demand.",
    payload: `{
  "action": "reallocate",
  "source_hubs": ["Westside Regional Medical Center"],
  "destination_hubs": ["Southern Cross Clinic"],
  "items": [{ "sku": "Lidocaine HCl", "quantity": 1200 }]
}`,
    tag: "Recommendation",
  },
  {
    time: "2026-05-27 21:07 UTC",
    title: "Cold Chain Feed Anomaly Detected",
    alert: "Sensor ingestion lag and audit sync failure",
    reasoning: "Gemini elevated the issue and prepared an incident response payload for immediate operator review.",
    payload: `{
  "incident": "cold_chain_audit",
  "priority": "high",
  "remediation": "reroute sensor telemetry through backup pipeline",
  "target": "logistics_ops"
}`,
    tag: "Alert",
  },
];

const tagVariant = (tag: string) => {
  if (tag === "Alert") return "destructive";
  if (tag === "Recommendation") return "secondary";
  return "default";
};

export function AILogs() {
  return (
    <section className="flex-1 flex flex-col overflow-hidden bg-background/60">
      <div className="flex h-16 items-center justify-between border-b border-border px-8 bg-card/80 shadow-sm">
        <div>
          <p className="text-xs uppercase tracking-[0.3em] text-emerald-300/80">Decision Intelligence</p>
          <h2 className="text-xl font-semibold tracking-tight text-foreground">Gemini AI Logs</h2>
        </div>
        <div className="rounded-2xl border border-emerald-700/40 bg-slate-900/80 px-4 py-2 text-sm text-emerald-200">
          Chronological reasoning history
        </div>
      </div>

      <div className="flex-1 overflow-auto p-8">
        <div className="grid gap-4 lg:grid-cols-3 mb-6">
          <Card className="border-emerald-700/40 bg-slate-950/80 shadow-xl shadow-emerald-950/10">
            <CardHeader>
              <CardTitle className="text-lg text-white">Decisions</CardTitle>
              <CardDescription className="text-slate-400">Recent AI reasoning events completed.</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="text-3xl font-semibold text-white">3</div>
            </CardContent>
          </Card>
          <Card className="border-teal-700/40 bg-slate-950/80 shadow-xl shadow-teal-950/10">
            <CardHeader>
              <CardTitle className="text-lg text-white">Review Ready</CardTitle>
              <CardDescription className="text-slate-400">High-confidence logs for human sign-off.</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="text-3xl font-semibold text-white">2</div>
            </CardContent>
          </Card>
          <Card className="border-slate-700/50 bg-slate-950/80 shadow-xl shadow-slate-950/10">
            <CardHeader>
              <CardTitle className="text-lg text-white">Payload Drafts</CardTitle>
              <CardDescription className="text-slate-400">Infrastructure payloads generated by Gemini.</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="text-3xl font-semibold text-white">3</div>
            </CardContent>
          </Card>
        </div>

        <div className="space-y-4">
          {aiLogEvents.map((event) => (
            <Card key={event.time} className="overflow-hidden border border-border bg-slate-950/90 shadow-lg shadow-slate-950/20">
              <CardHeader className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
                <div>
                  <div className="text-xs uppercase tracking-[0.2em] text-slate-500">{event.time}</div>
                  <CardTitle className="text-xl text-white">{event.title}</CardTitle>
                  <CardDescription className="text-slate-400">{event.alert}</CardDescription>
                </div>
                <Badge variant={tagVariant(event.tag)}>{event.tag}</Badge>
              </CardHeader>
              <CardContent className="space-y-4 border-t border-slate-800/70 pt-4">
                <div className="space-y-2 text-slate-300">
                  <p className="text-sm leading-7">{event.reasoning}</p>
                </div>
                <div className="rounded-2xl border border-slate-800 bg-slate-900/95 p-4 text-sm text-slate-200">
                  <pre className="whitespace-pre-wrap break-words font-mono text-slate-100">{event.payload}</pre>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>
    </section>
  );
}
